version: '3.1'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /golang_database_sample
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 18080:18080
    depends_on:
      - db
  
  db:
    image: postgres:14.2-alpine
    container_name: my_postgres_14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./docker/postgres/pgdata:/var/lib/postgresql/data
    - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
    - 25432:5432